<?xml version="1.0" encoding="utf-8"?>
<!-- Subset of Model Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD0_0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="dd15f284-0a37-430a-a88c-cf13719cc36f">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="dd15f284-0a37-430a-a88c-cf13719cc36f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>240 120 0 293.994469826 119.227194589 0 294.767275237 173.221664416 0 240.772805411 173.994469826 0 240 120 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ff1ca973-60e6-4d3c-b182-5f1c3620a27c">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="ff1ca973-60e6-4d3c-b182-5f1c3620a27c">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>240 300 0 292.917812242 310.756632722 0 282.16117952 363.674444964 0 229.243367278 352.917812242 0 240 300 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="726ccfc0-f61e-40fe-b075-f8fb96207ca5">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="726ccfc0-f61e-40fe-b075-f8fb96207ca5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>240 360 0 293.326294989 351.49669107 0 301.829603919 404.822986059 0 248.50330893 413.326294989 0 240 360 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="a60697ef-cc35-4086-8907-be333180f4c1">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="a60697ef-cc35-4086-8907-be333180f4c1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>240 180 0 280.028761718 216.244975311 0 243.783786408 256.273737029 0 203.755024689 220.028761718 0 240 180 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="325ea05e-a80a-4c79-a414-98067370b6cc">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="325ea05e-a80a-4c79-a414-98067370b6cc">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>240 240 0 284.815406089 270.126058108 0 254.689347981 314.941464196 0 209.873941892 284.815406089 0 240 240 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="62167adf-ebe6-4fa9-96d1-b7c6d3d65ac8">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="62167adf-ebe6-4fa9-96d1-b7c6d3d65ac8">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>360 120 0 413.239063428 129.033389468 0 404.20567396 182.272452896 0 350.966610532 173.239063428 0 360 120 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fb0106dc-d4ff-4fcd-9faf-0174b37e101f">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fb0106dc-d4ff-4fcd-9faf-0174b37e101f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>360 180 0 413.411028513 187.953743343 0 405.45728517 241.364771857 0 352.046256657 233.411028513 0 360 180 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="2b5d6477-4977-48d3-b625-47f0c2d6cb20">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="2b5d6477-4977-48d3-b625-47f0c2d6cb20">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>360 240 0 410.550530189 258.990626571 0 391.559903618 309.541156761 0 341.009373429 290.550530189 0 360 240 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="ed426f0a-f4f7-488d-b8c2-d0d49a530582">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="ed426f0a-f4f7-488d-b8c2-d0d49a530582">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>360 300 0 399.691779038 263.386304792 0 436.305474246 303.07808383 0 396.613695208 339.691779038 0 360 300 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b4dfe61a-7413-4579-9653-3d60168c359f">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="b4dfe61a-7413-4579-9653-3d60168c359f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>360 360 0 413.481013728 352.531320687 0 420.94969304 406.012334415 0 367.468679313 413.481013728 0 360 360 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="73e73072-c692-4efd-b0c2-3ec16e7e7a1b">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="73e73072-c692-4efd-b0c2-3ec16e7e7a1b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>300 240 0 353.981741438 238.595866361 0 355.385875077 292.5776078 0 301.404133639 293.981741438 0 300 240 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="7434e29c-4dee-43a2-8c7c-99608695aabb">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7434e29c-4dee-43a2-8c7c-99608695aabb">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>180 300 0 223.19994212 267.599922827 0 255.600019293 310.799864947 0 212.400077173 343.19994212 0 180 300 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3020a1a6-209b-4fed-9506-d57228106384">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3020a1a6-209b-4fed-9506-d57228106384">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>180 240 0 220.945399414 204.793831977 0 256.151567437 245.739231391 0 215.206168023 280.945399414 0 180 240 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fddf5116-8fd6-4a24-8716-eb0f21a19d0e">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fddf5116-8fd6-4a24-8716-eb0f21a19d0e">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>180 180 0 228.326455527 204.094681908 0 204.231773619 252.421137434 0 155.905318092 228.326455527 0 180 180 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="0a1b8e7e-0601-4cd9-bfdd-15b51280ee54">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="0a1b8e7e-0601-4cd9-bfdd-15b51280ee54">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>180 120 0 233.807446706 115.443830669 0 238.363616038 169.251277375 0 184.556169331 173.807446706 0 180 120 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="f34cf9d8-8b3e-424b-a0a1-d1a2f3e4a4d6">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f34cf9d8-8b3e-424b-a0a1-d1a2f3e4a4d6">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>300 120 0 353.064587514 130.007474806 0 343.057112708 183.072062319 0 289.992525194 173.064587514 0 300 120 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d23494fe-0532-4e99-b009-69109222de0b">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d23494fe-0532-4e99-b009-69109222de0b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>420 120 0 461.661731972 154.355495762 0 427.30623621 196.017227735 0 385.644504238 161.661731972 0 420 120 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="9beac2f5-37c0-4a71-a1ff-02e8ec9e14f2">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="9beac2f5-37c0-4a71-a1ff-02e8ec9e14f2">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>300 180 0 351.800292831 164.744520242 0 367.055772589 216.544813072 0 315.255479758 231.800292831 0 300 180 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="3157b443-1ce6-4a2e-b794-343822fc0762">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3157b443-1ce6-4a2e-b794-343822fc0762">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>300 360 0 350.228719658 340.173862667 0 370.054856991 390.402582324 0 319.826137333 410.228719658 0 300 360 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d558bc69-3a3f-4f24-80d5-a386ee58ff6b">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d558bc69-3a3f-4f24-80d5-a386ee58ff6b">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>300 300 0 350.246002098 280.217703037 0 370.028299061 330.463705136 0 319.782296963 350.246002098 0 300 300 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d757df68-6b8e-42a5-919a-71d97e74c956">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d757df68-6b8e-42a5-919a-71d97e74c956">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>420 360 0 472.468113577 347.229054161 0 485.239059417 399.697167738 0 432.770945839 412.468113577 0 420 360 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="1d5295c7-6c49-4a7f-83c6-b4557263ff6f">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="1d5295c7-6c49-4a7f-83c6-b4557263ff6f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>420 300 0 473.970623319 301.780960009 0 472.18966331 355.751583328 0 418.219039991 353.970623319 0 420 300 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="f4308b48-9963-424d-a278-ee9688903c97">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f4308b48-9963-424d-a278-ee9688903c97">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>420 240 0 463.143327549 272.475425909 0 430.66790164 315.618753458 0 387.524574091 283.143327549 0 420 240 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="d4698e3e-015d-4b78-91e8-bf020f1e1a9f">
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="d4698e3e-015d-4b78-91e8-bf020f1e1a9f">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>420 180 0 466.632867014 152.771784596 0 493.861082418 199.40465161 0 447.228215404 226.632867014 0 420 180 0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
</CityModel>