<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>LOD0_0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>0 0 0</gml:lowerCorner>
      <gml:upperCorner>4000 4000 25</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="1cb02c40-9d59-44e8-87b1-81b1fc9102e0">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>2003</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>5</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="0631e426-655a-4c91-beae-801f80c35301">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 0.0 0.0 49.0594415864 -22.5648219853 0.0 71.6242635717 26.4946196012 0.0 22.5648219853 49.0594415864 0.0 0.0 0.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="802c9f1e-056a-4f73-a9f1-164671a1fbe8">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1959</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="203d69fb-5311-4327-a819-fdfddce6d54a">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 60.0 0.0 53.8176458162 55.5659275153 0.0 58.2517183009 109.383573332 0.0 4.43407248466 113.817645816 0.0 0.0 60.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="1114eab8-35a0-4860-bb6e-2cb7465dee74">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1964</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="7084c636-1cfd-406f-ae28-67a4e14734ee">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 120.0 0.0 51.2034932095 137.152325881 0.0 34.0511673281 188.355819091 0.0 -17.1523258814 171.20349321 0.0 0.0 120.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="da05f6d9-6b7d-4eb7-a748-99bcd31e2a55">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1999</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="882ff44c-82da-42c3-985a-005c3db4cec5">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 180.0 0.0 44.0659830133 211.212003157 0.0 12.8539798563 255.27798617 0.0 -31.212003157 224.065983013 0.0 0.0 180.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="b6d7a83c-93b8-4601-9297-2e4a72c3617a">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1962</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>4</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="9446d3aa-6b3e-4dda-8ea2-68448d78d4c0">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 240.0 0.0 52.9365054999 229.33574262 0.0 63.6007628797 282.27224812 0.0 10.6642573798 292.9365055 0.0 0.0 240.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="45895e46-5b57-4731-b74c-a6b73fccef7b">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1945</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="3e0a0bc9-66b6-4c87-99e5-1218591faae7">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 300.0 0.0 52.046106441 314.394540782 0.0 37.6515656588 366.440647223 0.0 -14.3945407822 352.046106441 0.0 0.0 300.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="76b0e9dd-a8c7-4e60-bdfd-c24f7864920a">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1990</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>3</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="fc2fe778-a3df-46a0-89e7-60e1573b18d1">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 360.0 0.0 53.0888819524 369.877783812 0.0 43.2110981403 422.966665765 0.0 -9.87778381217 413.088881952 0.0 0.0 360.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="eba9a6fb-3d0b-4c6a-a291-2e2fc5665d32">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1954</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="10dbbafb-c2c2-461e-8e21-59b82b2dda52">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 420.0 0.0 52.7963403514 431.337832487 0.0 41.4585078648 484.134172838 0.0 -11.3378324866 472.796340351 0.0 0.0 420.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="59be0f3b-f3df-406e-9ba5-6fd07bb8b3a6">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1958</bldg:yearOfConstruction>
      <bldg:function>Industrial</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="c29f9ce5-c70f-4fb8-84ce-2c361a01d502">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 480.0 0.0 53.9794692341 478.511073807 0.0 55.4683954269 532.490543041 0.0 1.48892619283 533.979469234 0.0 0.0 480.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="fc8d5338-2c14-455e-bbb0-9f5319735e52">
      <bldg:roofType>Flat</bldg:roofType>
      <bldg:yearOfConstruction>1973</bldg:yearOfConstruction>
      <bldg:function>Residential</bldg:function>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:storeysAboveGround>1</bldg:storeysAboveGround>
      <bldg:lod0FootPrint>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="ef509dd6-2c58-4e73-8dfb-25235542a3dd">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>0.0 540.0 0.0 52.3431058157 553.274007442 0.0 39.0690983738 605.617113258 0.0 -13.2740074419 592.343105816 0.0 0.0 540.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </bldg:lod0FootPrint>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
